Sml workload vpc
tamer4osman/CAPCI_G1 pull request #2
Opened 2022-12-14 00:02 UTC by rashidatsalau

Kindly review my code. the ticket number is 03. thank you.

2022-12-14 08:03 UTC, olga-matusik requested changes

2022-12-14 08:03 UTC, olga-matusik commented on migration-lab/terraform/migration_vpc/vpc_peering.tf
> +} #in the peer_vpc_id, it needs to correspond to the on-prem.
I saw in the terraform documentation (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_peering_connection) that we can use `auto_accept = true` if both VPCs are in the same account and region.

2022-12-14 08:36 UTC, olga-matusik requested changes
According to the ticket we need also some NACL rules here.

2022-12-14 13:30 UTC, olga-matusik requested changes

2022-12-14 13:30 UTC, olga-matusik commented on migration-lab/terraform/migration_vpc/NACL.tf
> +    rule_no    = 200
rule_no here can also be 100

2022-12-14 13:30 UTC, olga-matusik commented on migration-lab/terraform/migration_vpc/NACL.tf
> +    protocol   = "-1"
I think you don't need " ", just -1 is enough

2022-12-14 13:30 UTC, olga-matusik commented on migration-lab/terraform/migration_vpc/NACL.tf
> +}
I think we need to allow also the traffic from staging area subnet, I checked it on my account, and without that all traffic is denied...

2022-12-14 14:04 UTC, olga-matusik approved these changes
LGTM! 👍

2022-12-15 12:57 UTC, zeynepiskender approved these changes

2022-12-15 13:22 UTC, merged